/**
 * Canonical set of API error codes used across the system.
 * Source: docs/06-api/error-response.md, docs/06-api/authentication.md,
 * docs/06-api/employee/*.md.
 *
 * Do not hard-code these strings inline in services/controllers; always
 * reference this enum so the set of valid codes stays discoverable in one place.
 */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_DISABLED = 'USER_DISABLED',
  CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID',
  PASSWORD_POLICY_FAILED = 'PASSWORD_POLICY_FAILED',

  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_CODE_EXISTS = 'EMPLOYEE_CODE_EXISTS',
  EMPLOYEE_EMAIL_EXISTS = 'EMPLOYEE_EMAIL_EXISTS',
  EMPLOYEE_MISSING_EMAIL = 'EMPLOYEE_MISSING_EMAIL',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_TYPE_NOT_FOUND = 'ORGANIZATION_TYPE_NOT_FOUND',
  ORGANIZATION_TYPE_NAME_EXISTS = 'ORGANIZATION_TYPE_NAME_EXISTS',
  // Workflow module (WORK-028 adds all of these in one pass, including the
  // ones only WORK-029's action engine throws, so this file is edited once).
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  WORKFLOW_CODE_EXISTS = 'WORKFLOW_CODE_EXISTS',
  WORKFLOW_NOT_ACTIVE = 'WORKFLOW_NOT_ACTIVE',
  WORKFLOW_HAS_NO_STEPS = 'WORKFLOW_HAS_NO_STEPS',
  WORKFLOW_HAS_ACTIVE_REQUESTS = 'WORKFLOW_HAS_ACTIVE_REQUESTS',
  WORKFLOW_STEP_NOT_FOUND = 'WORKFLOW_STEP_NOT_FOUND',
  WORKFLOW_REQUEST_NOT_FOUND = 'WORKFLOW_REQUEST_NOT_FOUND',
  WORKFLOW_REQUEST_STALE = 'WORKFLOW_REQUEST_STALE',
  WORKFLOW_REQUEST_INVALID_STATE = 'WORKFLOW_REQUEST_INVALID_STATE',
  WORKFLOW_ACTION_NOT_ALLOWED = 'WORKFLOW_ACTION_NOT_ALLOWED',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_TOKEN_INVALID = 'INVITATION_TOKEN_INVALID',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
